### ISSUE TITLE
Update PyPI package information with new home page pointing to this repository (copy)

### ISSUE THREAD

**Issue by jamescooke** [davidlbaird/pyfakefs#33]
Please update the page for [pyfakefs on PyPI](https://pypi.python.org/pypi/pyfakefs/2.4) with URLs that point to this repo. This will help people like me to be certain that this is the official copy that should be contributed to.

The problem is that there are a bunch of clones and there is no certainty around which one should receive community efforts. https://github.com/search?utf8=✓&q=pyfakefs

If this repo is not to be the official, then maybe you can help to transfer over to this one, which appears to have more interest and collaboration already: https://github.com/jmcgeheeiv/pyfakefs/issues/44

**Comment by jmcgeheeiv** [comment]
David,
I am getting requests to update PyPi pyfakefs with jmcgeheeiv/pyfakefs.  Would be willing to hand over of share control of PyPi pyfakefs to me?  I'll take good care of it.

**Comment by codito** [comment]
+1, there are [several enhancements](https://github.com/jmcgeheeiv/pyfakefs/commits/master) in jmcgeheeiv/pyfakefs fork. It would be nice to see the library updated in pypi.

**Comment by piotrkilczuk** [comment]
+1 for @jmcgeheeiv

**Comment by duncanwp** [comment]
+1

**Comment by convolu** [comment]
+1, please update the package with the jmcgeheeiv/pyfakefs fork

**Comment by mshawcroft** [comment]
+1 for @jmcgeheeiv

**Comment by jamescooke** [comment]
:+1: for @jmcgeheeiv ... I agree and will be focussing my efforts on https://github.com/jmcgeheeiv/pyfakefs/

**Comment by jamescooke** [comment]
... leaving this issue open. Hopefully it'll help people to find the new repo :arrow_up:

**Comment by jamescooke** [comment]
https://pypi.python.org/pypi/pyfakefs is updated with the new repo and 2.7 release.
